server:
  port: 8000
  servlet:
    context-path: /

#数据源的配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      initial-size: 10
      max-active: 50
      maxWait: 15000
      validationQuery: SELECT 'x'    #验证连接
      #配置监控页面
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        allow:
        deny: 192.168.9.123
        url-pattern: '/druid/*'
        enabled: true   #启用监控页面
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: '/*'
        enabled: true
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

#mybatis的配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   #注入核心 配置文件
  mapper-locations:                            #配置映射文件

#shiro的定义配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  unauthorized-url: /unauthorize.html
  anon-urls:
  - /index.html*
  - /index.htm*
  - /unauthorize.html*
  - /resources/**   #放行静态文件
  - /login/toLogin*
  - /login/login
  logout-url: /login/logout
  authc-urls:
  - /**